# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairs_to_membership_cpp <- function(pairs, num_records) {
    .Call('_clevr_pairs_to_membership_cpp', PACKAGE = 'clevr', pairs, num_records)
}

